workflows:
  ios-unsigned:
    name: Flutter iOS Unsigned IPA
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      flutter: stable
      cocoapods: default

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

      - name: Package IPA
        script: |
          rm -rf build/ipa
          mkdir -p build/ipa/Payload

          cp -R build/ios/iphoneos/Runner.app build/ipa/Payload/

          cd build/ipa
          zip -r Runner.ipa Payload

    artifacts:
      - build/ipa/Runner.ipa
